services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    healthcheck: 
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start_period: 10s
    ports:
      - 5672:5672
      - 15692:15692

  gateway:
    build: ./app
    container_name: gateway
    ports:
      - 4040:4040
    depends_on:
      rabbitmq:
        condition: service_healthy

  delivery:
    build: ./delivery
    container_name: delivery
    expose:
      - 4044
    depends_on:
      rabbitmq:
        condition: service_healthy
        # restart: true
  
  orders:
    build: ./orders
    container_name: orders
    expose:
      - 4042
    depends_on:
      rabbitmq:
        condition: service_healthy

  products:
    build: ./products
    container_name: products
    expose:
      - 4041
    depends_on:
      rabbitmq:
        condition: service_healthy

  payments:
    build: ./payments
    container_name: payments
    expose:
      - 4043
    depends_on:
      rabbitmq:
        condition: service_healthy