services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    healthcheck: 
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start_period: 10s
    ports:
      - 5672:5672
      - 15692:15692

  delivery:
    build: ./delivery
    container_name: delivery
    ports:
      - 4044:4044
    depends_on:
      rabbitmq:
        condition: service_healthy
        # restart: true
        
  gateway:
    build: ./app
    container_name: gateway
    ports:
      - 4040:4040
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  orders:
    build: ./orders
    container_name: orders
    ports:
      - 4042:4042
    depends_on:
      rabbitmq:
        condition: service_healthy